In [861]:
import plotly.graph_objects as go
import os
import pandas as pd
from config import *

In [862]:
timestamps = [
    "20250115_02-02-09", #1
    "20250115_02-18-54", #2
    "20250115_14-59-27", #3
    "20250115_21-28-12", #4 Very low forecast quality
    "20250115_21-51-57", #5 Higher RE gen than thermal gen + different target price parameters
    "20250115_22-12-28", #6 same as #5 but no matches
    "20250115_23-45-23", #7 Fixed aggressiveness update bug                                             show
    "20250116_00-23-53", #8 Marginal costs differences higher                                           show
    "20250116_01-49-38", #9 Different forecasting quality between agents
    "20250116_12-53-07", #10 Different forecasting quality between agents
    "20250123_19-41-25", #11 Allows for negative prices                                                 show
    "20250123_22-32-55", #12 Allows for negative prices; No Feed-In obligation                          show
    "20250124_01-30-34", #13 RL Agent
    "20250124_22-30-31", #14 RL Agent
    "20250127_20-55-19", #15 RL Agent
    "20250128_12-24-28",
    "20250701_22-06-32", #17 Random seed set - without RL
    "20250701_22-22-08", #18 Random seed set - with untrained RL
    "20250704_06-09-23", #19 Random seed set - with trained RL
]

# Choose which run to plot
choose_run = -4

In [863]:
plot_latest_run = False if 0 < choose_run <= len(timestamps) else True

# List all folders in the directory
runs = [f for f in os.listdir("csv") if os.path.isdir(os.path.join("csv", f))]

if plot_latest_run:
    timestamp = sorted(runs)[choose_run]
else:
    timestamp = timestamps[choose_run-1]

df_bidders = pd.read_csv(f"csv/{timestamp}/bidders.csv", delimiter=";")
df_game_data = pd.read_csv(f"csv/{timestamp}/game_data.csv", delimiter=";")
df_bid_logs = pd.read_csv(f"csv/{timestamp}/bid_logs.csv", delimiter=";")

df_x_demand = pd.read_csv(f"csv/{timestamp}/x_demand.csv", delimiter=";")
df_x_bought = pd.read_csv(f"csv/{timestamp}/x_bought.csv", delimiter=";")
df_x_sold = pd.read_csv(f"csv/{timestamp}/x_sold.csv", delimiter=";")
df_x_re_capacity = pd.read_csv(f"csv/{timestamp}/x_re_cap.csv", delimiter=";")
df_x_re_gen = pd.read_csv(f"csv/{timestamp}/x_re_gen.csv", delimiter=";")
df_x_th_gen = pd.read_csv(f"csv/{timestamp}/x_th_gen.csv", delimiter=";")
df_x_th_start = pd.read_csv(f"csv/{timestamp}/x_th_start.csv", delimiter=";")

df_ask_prices = pd.read_csv(f"csv/{timestamp}/ask_prices.csv", delimiter=";")
df_bid_prices = pd.read_csv(f"csv/{timestamp}/bid_prices.csv", delimiter=";")
df_ask_agg = pd.read_csv(f"csv/{timestamp}/ask_agg.csv", delimiter=";")
df_bid_agg = pd.read_csv(f"csv/{timestamp}/bid_agg.csv", delimiter=";")
df_target_price_param = pd.read_csv(f"csv/{timestamp}/target_price_param.csv", delimiter=";")
df_limit_buy = pd.read_csv(f"csv/{timestamp}/limit_buy.csv", delimiter=";")
df_limit_sell = pd.read_csv(f"csv/{timestamp}/limit_sell.csv", delimiter=";")
df_target_asks = pd.read_csv(f"csv/{timestamp}/target_asks.csv", delimiter=";")
df_target_bids = pd.read_csv(f"csv/{timestamp}/target_bids.csv", delimiter=";")

df_market_positions = pd.read_csv(f"csv/{timestamp}/market_positions.csv", delimiter=";")
df_payoffs = pd.read_csv(f"csv/{timestamp}/payoffs.csv", delimiter=";")
df_revenues = pd.read_csv(f"csv/{timestamp}/revenues.csv", delimiter=";")
df_expenses = pd.read_csv(f"csv/{timestamp}/expenses.csv", delimiter=";")
df_prod_costs = pd.read_csv(f"csv/{timestamp}/prod_costs.csv", delimiter=";")
df_penalty_imbalances = pd.read_csv(f"csv/{timestamp}/penalty_imbalances.csv", delimiter=";")
df_imbalances = pd.read_csv(f"csv/{timestamp}/imbalances.csv", delimiter=";")

bidder_colors = ['green', 'purple', 'orange', 'brown', 'pink', 'olive']
ask_color = 'red'
bid_color = 'blue'
imbalance_color = 'darkgrey'
match_color = 'black'
marginal_cost_color = 'cyan'
background = 'white'
paper_bgcolor = 'white'
grid_color = 'lightgrey'
axis_color = 'black'
font_color = 'black'
width = 1000
height = 600



frame = [
        # Top border
        dict(type='line', x0=0, x1=1, y0=1, y1=1, xref='paper', yref='paper',
             line=dict(color='black', width=1)),
        # Bottom border
        dict(type='line', x0=0, x1=1, y0=0, y1=0, xref='paper', yref='paper',
             line=dict(color='black', width=1)),
        # Left border
        dict(type='line', x0=0, x1=0, y0=0, y1=1, xref='paper', yref='paper',
             line=dict(color='black', width=1)),
        # Right border
        dict(type='line', x0=1, x1=1, y0=0, y1=1, xref='paper', yref='paper',
             line=dict(color='black', width=1))
    ]

In [864]:

print(f"Plotting run: {timestamp}\n")

print(f"Total: {df_game_data['last_event'].value_counts()}\n")

print(f"Matches at: {df_bid_logs[df_bid_logs['match_flag'] == 'match'].index}\n")

for i in range(n):
    print(f"Bidder_{i}: {df_bid_logs[df_bid_logs['bidder'] == i]['match_flag'].value_counts()}")

Plotting run: 20260106_15-49-17

Total: last_event
bid      82
match    65
ask      53
Name: count, dtype: int64

Matches at: Index([ 21,  32,  36,  37,  38,  40,  42,  45,  47,  48,  49,  50,  51,  52,
        55,  57,  60,  62,  64,  67,  71,  74,  76,  78,  80,  82,  83,  84,
        86,  87,  88,  89,  91,  92,  94,  95,  97, 100, 108, 113, 115, 116,
       118, 121, 126, 129, 131, 134, 136, 137, 139, 144, 147, 153, 157, 159,
       160, 161, 163, 165, 170, 173, 175, 177],
      dtype='int64')

Bidder_0: match_flag
match    12
ask      11
bid      11
Name: count, dtype: int64
Bidder_1: match_flag
ask      13
bid      13
match    10
Name: count, dtype: int64
Bidder_2: match_flag
bid      19
match     9
ask       7
Name: count, dtype: int64
Bidder_3: match_flag
bid      12
match    10
ask       8
Name: count, dtype: int64
Bidder_4: match_flag
bid      13
ask      12
match    10
Name: count, dtype: int64
Bidder_5: match_flag
bid      14
match    13
ask       2
Name: count, dtype: int64

In [865]:
df_bid_logs

,Unnamed: 0,bidder,price,volume,transaction_price,match_flag,buyer,seller
0,1,3.0,38.917902,306.692122,NaN,ask,NaN,NaN
1,2,1.0,38.553512,286.237137,NaN,ask,NaN,NaN
2,3,5.0,15.176039,84.760666,NaN,ask,NaN,NaN
3,4,3.0,-15.200539,147.745324,NaN,bid,NaN,NaN
4,5,2.0,-12.055925,270.346651,NaN,bid,NaN,NaN
...,...,...,...,...,...,...,...,...
194,195,5.0,15.013472,156.848669,NaN,bid,NaN,NaN
195,196,3.0,16.954332,44.813682,NaN,bid,NaN,NaN
196,197,0.0,16.991398,254.863018,NaN,bid,NaN,NaN
197,198,4.0,17.035381,2.041577,NaN,bid,NaN,NaN
198,199,1.0,17.087701,78.946673,NaN,bid,NaN,NaN

In [866]:
### Payoffs

fig = go.Figure()

for bidder in range(1, n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_payoffs[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder}',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Payoffs',
    width=width,
    height=height,
    plot_bgcolor=background,
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [867]:
### Imbalance vs Production

for bidder in range(n):
    fig = go.Figure()

    # Add marker for 'transaction price bids'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['buyer'] == bidder)].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['buyer'] == bidder), 'transaction_price'],
        mode='markers',
        name=f'Transaction price bids',
        line=dict(width=2, color=bid_color),
        marker=dict(symbol='x', size=10), 
        yaxis='y'
    ))
    
    # Add marker for 'transaction price asks'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['seller'] == bidder)].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['seller'] == bidder), 'transaction_price'],
        mode='markers',
        name=f'Transaction price asks',
        line=dict(width=2, color=ask_color),
        marker=dict(symbol='x', size=10), 
        yaxis='y'
    ))

    # Add marker for 'bid price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'bid')].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'bid'), 'price'],
        mode='markers',
        name=f'Bids',
        line=dict(width=2, color=bid_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'ask price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'ask')].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'ask'), 'price'],
        mode='markers',
        name=f'Asks',
        line=dict(width=2, color=ask_color),  # Adjust line width if necessary
        yaxis='y'
    ))
        
    # Add line for 'Actual prices'
    fig.add_trace(go.Scatter(
        x=df_bid_prices.index,
        y=df_bid_prices[f'bidder_{bidder}'],
        mode='lines',
        name='Bid prices',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=bid_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add line for 'Actual prices'
    fig.add_trace(go.Scatter(
        x=df_ask_prices.index,
        y=df_ask_prices[f'bidder_{bidder}'],
        mode='lines',
        name='Ask prices',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=ask_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add line for 'Marginal costs'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.index,
        y=[df_bidders['true_costs'][bidder]] * len(df_bid_logs),
        mode='lines',
        name='Marginal costs',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=marginal_cost_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add bar for 'Thermal prod'
    fig.add_trace(go.Bar(
        x=df_x_th_gen[f'bidder_{bidder}'].index,
        y=df_x_th_gen[f'bidder_{bidder}'],
        name='Thermal gen',
        width=1,
        yaxis='y2',
        marker=dict(color='brown'),
    ))
    
    # Add bar for 'RE prod'
    fig.add_trace(go.Bar(
        x=df_x_re_gen[f'bidder_{bidder}'].index,
        y=df_x_re_gen[f'bidder_{bidder}'],
        name='RE gen',
        width=1,
        yaxis='y2',
        marker=dict(color='green'),
    ))
    
    # Add line for 'Imbalance'
    fig.add_trace(go.Scatter(
        x=df_imbalances[f'bidder_{bidder}'].index,
        y=df_imbalances[f'bidder_{bidder}'] + df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name='Imbalance',
        yaxis='y2',
        line=dict(width=2, color=imbalance_color)  # Adjust line width if necessary
    ))
    
    # Add outline for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position outline',
        showlegend=False,
        line=dict(width=4, color='black'),  # Adjust line width if necessary
        yaxis='y2'
    ))

    # Add line for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position',
        line=dict(width=3, color=bidder_colors[bidder]),  # Adjust line width if necessary
        yaxis='y2'
    ))
    
    demand_mean = -2500
    max_imbalance = df_imbalances[f'bidder_{bidder}'].abs().max()
    min_market_position = df_market_positions[f'bidder_{bidder}'].min()
    max_market_position = df_market_positions[f'bidder_{bidder}'].max()
    
    range_y = [min_price - 5, max_price + 5]
    range_y2 = [min(0, min_market_position - 100), max_market_position + 100] if bidder != 0 else [demand_mean - max_imbalance, demand_mean + max_imbalance]
    
    # Update layout
    fig.update_layout(
        title=f'Market position and production [Bidder {bidder}]',
        barmode='stack',
        width=width,
        height=height,
        plot_bgcolor=background,
        paper_bgcolor=paper_bgcolor,
        font_color=font_color,
        xaxis=dict(
            title='Timestep',
            mirror=True,
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
        ),
        yaxis=dict(
            title='Price [€/MWh]',
            side='right',
            overlaying='y2',
            position=1,
            range=range_y,
            tickcolor=grid_color,
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
        ),
        yaxis2=dict(
            title='Volume [MWh]',
            position=0,
            range=range_y2,
            ticks='',
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
            showgrid=False,
            ),
        legend=dict(
            x=1.1
        ),
        #shapes=frame, 
    )
    
    # Show the plot
    fig.show()

In [868]:
### Payoffs

fig = go.Figure()

for bidder in range(1, n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_payoffs[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder}',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Payoffs',
    width=width,
    height=height,
    plot_bgcolor=background,
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [869]:
### Bid-Ask spread

fig = go.Figure()

# Add lines for 'bid'
fig.add_trace(go.Scatter(
    #x=bid_data['index'],
    y=df_game_data['top_bid'],
    mode='lines',
    name='Top bid',
    line=dict(width=2, color=bid_color)  # Adjust line width if necessary
))

# Add lines for 'ask'
fig.add_trace(go.Scatter(
    y=df_game_data['top_ask'],
    mode='lines',
    name='Top Ask',
    marker=dict(size=8, color=ask_color)  # Adjust point size if necessary
))

# Add lines for 'Day-Ahead Preis'
fig.add_trace(go.Scatter(
    #x=bid_data['index'],
    y=[df_game_data.loc[0, 'marginal_price'] for i in range(len(df_game_data))],
    mode='lines',
    name='Day-Ahead price',
    line=dict(width=2)  # Adjust line width if necessary
))

# Add points for 'matches'
fig.add_trace(go.Scatter(
    y=df_game_data['transaction_price'],
    mode='markers',
    name='Matches',
    marker=dict(size=8, color=match_color, symbol='x')  # Adjust point size if necessary
))

# Update layout
fig.update_layout(
    title='Bid-Ask spread',
    legend_title='Type',
    width=width,
    height=height,
    plot_bgcolor=background,
    paper_bgcolor=paper_bgcolor,
    font_color=font_color,
    xaxis=dict(
        title='Timestep',
        mirror=True,
        showline=True,
        linecolor=axis_color,
        gridcolor=grid_color,
    ),
    yaxis=dict(
        title='Price [€/MWh]',
        mirror=True,
        range=[min_price, max_price],
        tickcolor=grid_color,
        showline=True,
        linecolor=axis_color,
        gridcolor=grid_color,
    ),
)

# Show the plot
fig.show()

In [870]:
### Imbalance vs Market position

for bidder in range(n):
    fig = go.Figure()

    # Add marker for 'bid price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'bid')].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'bid'), 'price'],
        mode='markers',
        name=f'Bids',
        line=dict(width=2, color=bid_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'ask price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'ask')].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'ask'), 'price'],
        mode='markers',
        name=f'Asks',
        line=dict(width=2, color=ask_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'transaction price bids'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['buyer'] == bidder)].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['buyer'] == bidder), 'transaction_price'],
        mode='markers',
        name=f'Transaction price bids',
        line=dict(width=2, color=bid_color),
        marker=dict(symbol='x', size=10), 
        yaxis='y'
    ))
    
    # Add marker for 'transaction price asks'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['seller'] == bidder)].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['seller'] == bidder), 'transaction_price'],
        mode='markers',
        name=f'Transaction price asks',
        line=dict(width=2, color=ask_color),
        marker=dict(symbol='x', size=10), 
        yaxis='y'
    ))
        
    # Add line for 'Actual prices'
    fig.add_trace(go.Scatter(
        x=df_bid_prices.index,
        y=df_bid_prices[f'bidder_{bidder}'],
        mode='lines',
        name='Bid prices',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=bid_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add line for 'Actual prices'
    fig.add_trace(go.Scatter(
        x=df_ask_prices.index,
        y=df_ask_prices[f'bidder_{bidder}'],
        mode='lines',
        name='Ask prices',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=ask_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add line for 'Marginal costs'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.index,
        y=[df_bidders['true_costs'][bidder]] * len(df_bid_logs),
        mode='lines',
        name='Marginal costs',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=marginal_cost_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add line for 'Imbalance'
    fig.add_trace(go.Scatter(
        x=df_imbalances[f'bidder_{bidder}'].index,
        y=df_imbalances[f'bidder_{bidder}'] + df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name='Imbalance',
        yaxis='y2',
        line=dict(width=2, color=imbalance_color)  # Adjust line width if necessary
    ))
    
    # Add outline for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position outline',
        showlegend=False,
        line=dict(width=4, color='black'),  # Adjust line width if necessary
        yaxis='y2'
    ))

    # Add line for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position',
        line=dict(width=3, color=bidder_colors[bidder]),  # Adjust line width if necessary
        yaxis='y2'
    ))
    
    demand_mean = -2000
    max_imbalance = df_imbalances[f'bidder_{bidder}'].abs().max()
    
    range_y = [min_price, max_price]
    range_y2 = [0, 1000] if bidder != 0 else [demand_mean - max_imbalance, demand_mean + max_imbalance]
    
    # Update layout
    fig.update_layout(
        title=f'Market position and production [Bidder {bidder}]',
        barmode='stack',
        width=width,
        height=height,
        plot_bgcolor=background,
        paper_bgcolor=paper_bgcolor,
        font_color=font_color,
        #margin=dict(l=0, r=0, t=0, b=0),
        xaxis=dict(
            title='Timestep',
            mirror=True,
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
        ),
        yaxis=dict(
            title='Price [€/MWh]',
            side='right',
            overlaying='y2',
            #position=1,
            range=range_y,
            tickcolor=grid_color,
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
        ),
        yaxis2=dict(
            title='Volume [MWh]',
            #position=-1,
            range=range_y2,
            ticks='',
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
            showgrid=False,
            ),
        legend=dict(
            x=1.1
        ),
        #shapes=frame, 
    )
    
    # Show the plot
    fig.show()

In [871]:
### Limits

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_limit_buy[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} limit buy',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_limit_sell[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} limit sell',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
# Update layout
fig.update_layout(
    title='Limits',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [872]:
### Target prices

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_target_asks[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} target ask',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_target_bids[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} target bid',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))
    
# Update layout
fig.update_layout(
    title='Target prices',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [873]:
### Aggressiveness

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_ask_agg[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Ask',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_bid_agg[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Bid',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Aggressiveness',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type',
    yaxis=dict(range=[-1, 1])
)

# Show the plot
fig.show()

In [874]:
### Target price param

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_target_price_param[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Target price param',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Target price param',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type',
    width=1000,
    height=600,
    plot_bgcolor=background,
)

# Show the plot
fig.show()

In [875]:
### Imbalance price

fig_volatility = go.Figure()

fig_volatility.add_trace(go.Scatter
(
    x=df_game_data.index,
    y=df_game_data['imbalance_penalty_factor'],
    mode='lines',
    name='Volatility',
    line=dict(width=2)
))

fig_volatility.update_layout(title='Imbalance penalty price')
fig_volatility.show()

In [876]:
### Payoffs

fig = go.Figure()

for bidder in range(1, n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_payoffs[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder}',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Payoffs',
    width=width,
    height=height,
    plot_bgcolor=background,
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [877]:
### Volatility

fig_volatility = go.Figure()

fig_volatility.add_trace(go.Scatter
(
    x=df_game_data.index,
    y=df_game_data['volatility'],
    mode='lines',
    name='Volatility',
    line=dict(width=2)
))

fig_volatility.update_layout(
    title='Volatility',
    width=width,
    height=height,
    plot_bgcolor=background,
)
fig_volatility.show()

In [878]:
df_x_th_start

     Unnamed: 0  bidder_0  bidder_1  bidder_2  bidder_3  bidder_4  bidder_5
0             1       0.0       2.0       4.0       0.0  0.000000       4.0
1             2       0.0       2.0       4.0       0.0  0.000000       4.0
2             3       0.0       4.0       6.0       0.0  0.000000       6.0
3             4       0.0       2.0       8.0       2.0  0.000000       8.0
4             5       0.0       4.0      10.0       0.0  0.000000      10.0
..          ...       ...       ...       ...       ...       ...       ...
194         195       0.0     300.0     300.0     124.0  2.272697       0.0
195         196       0.0     300.0     300.0     126.0  2.761995       0.0
196         197       0.0     300.0     300.0     128.0  2.331348       0.0
197         198       0.0     300.0     300.0     130.0  2.041577       0.0
198         199       0.0     300.0     300.0     132.0  2.135988       0.0

[199 rows x 7 columns]

In [879]:
### x_th_start

fig = go.Figure()

for bidder in range(1, n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_x_th_start[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder}',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='x_th_start',
    width=width,
    height=height,
    plot_bgcolor=background,
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [880]:
### Imbalance vs Production

for bidder in range(n):
    fig = go.Figure()
        
    # Add line for 'x_th_start'
    fig.add_trace(go.Scatter(
        x=df_x_th_start.index,
        y=df_x_th_start[f'bidder_{bidder}'],
        mode='lines',
        name='x_th_start',
        yaxis='y2',
        opacity=0.75,
        line=dict(width=2, color=match_color)  # Adjust line width if necessary
    ))
    
    # Add bar for 'Thermal prod'
    fig.add_trace(go.Bar(
        x=df_x_th_gen[f'bidder_{bidder}'].index,
        y=df_x_th_gen[f'bidder_{bidder}'],
        name='Thermal gen',
        width=1,
        yaxis='y2',
        marker=dict(color='brown'),
    ))
    
    # Add bar for 'RE prod'
    fig.add_trace(go.Bar(
        x=df_x_re_gen[f'bidder_{bidder}'].index,
        y=df_x_re_gen[f'bidder_{bidder}'],
        name='RE gen',
        width=1,
        yaxis='y2',
        marker=dict(color='green'),
    ))
    
    # Add line for 'Imbalance'
    fig.add_trace(go.Scatter(
        x=df_imbalances[f'bidder_{bidder}'].index,
        y=df_imbalances[f'bidder_{bidder}'] + df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name='Imbalance',
        yaxis='y2',
        line=dict(width=2, color=imbalance_color)  # Adjust line width if necessary
    ))
    
    # Add outline for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position outline',
        showlegend=False,
        line=dict(width=4, color='black'),  # Adjust line width if necessary
        yaxis='y2'
    ))

    # Add line for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position',
        line=dict(width=3, color=bidder_colors[bidder]),  # Adjust line width if necessary
        yaxis='y2'
    ))
    
    demand_mean = -2500
    max_imbalance = df_imbalances[f'bidder_{bidder}'].abs().max()
    min_market_position = df_market_positions[f'bidder_{bidder}'].min()
    max_market_position = df_market_positions[f'bidder_{bidder}'].max()
    
    range_y = [min_price - 5, max_price + 5]
    range_y2 = [min(0, min_market_position - 100), max_market_position + 100] if bidder != 0 else [demand_mean - max_imbalance, demand_mean + max_imbalance]
    
    # Update layout
    fig.update_layout(
        title=f'Market position and production [Bidder {bidder}]',
        barmode='stack',
        width=width,
        height=height,
        plot_bgcolor=background,
        paper_bgcolor=paper_bgcolor,
        font_color=font_color,
        xaxis=dict(
            title='Timestep',
            mirror=True,
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
        ),
        yaxis=dict(
            title='Price [€/MWh]',
            side='right',
            overlaying='y2',
            position=1,
            range=range_y,
            tickcolor=grid_color,
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
        ),
        yaxis2=dict(
            title='Volume [MWh]',
            position=0,
            range=range_y2,
            ticks='',
            showline=True,
            linecolor=axis_color,
            gridcolor=grid_color,
            showgrid=False,
            ),
        legend=dict(
            x=1.1
        ),
        #shapes=frame, 
    )
    
    # Show the plot
    fig.show()