In [945]:
import plotly.graph_objects as go
import os
import pandas as pd
from config import *

In [946]:
timestamps = [
    "20250115_02-02-09", #1
    "20250115_02-18-54", #2
    "20250115_14-59-27", #3
]

# Choose which run to plot
choose_run = 0

In [947]:
n = n-1

In [948]:
plot_latest_run = False if 0 < choose_run <= len(timestamps) else True

# List all folders in the directory
runs = [f for f in os.listdir("csv") if os.path.isdir(os.path.join("csv", f))]

if plot_latest_run:
    timestamp = sorted(runs)[-1]
else:
    timestamp = timestamps[choose_run]

df_bidders = pd.read_csv(f"csv/{timestamp}/bidders.csv", delimiter=";")
df_game_data = pd.read_csv(f"csv/{timestamp}/game_data.csv", delimiter=";")
df_bid_logs = pd.read_csv(f"csv/{timestamp}/bid_logs.csv", delimiter=";")

df_x_demand = pd.read_csv(f"csv/{timestamp}/x_demand.csv", delimiter=";")
df_x_bought = pd.read_csv(f"csv/{timestamp}/x_bought.csv", delimiter=";")
df_x_sold = pd.read_csv(f"csv/{timestamp}/x_sold.csv", delimiter=";")
df_x_re_capacity = pd.read_csv(f"csv/{timestamp}/x_re_cap.csv", delimiter=";")
df_x_re_gen = pd.read_csv(f"csv/{timestamp}/x_re_gen.csv", delimiter=";")
df_x_th_gen = pd.read_csv(f"csv/{timestamp}/x_th_gen.csv", delimiter=";")

df_ask_prices = pd.read_csv(f"csv/{timestamp}/ask_prices.csv", delimiter=";")
df_bid_prices = pd.read_csv(f"csv/{timestamp}/bid_prices.csv", delimiter=";")
df_ask_agg = pd.read_csv(f"csv/{timestamp}/ask_agg.csv", delimiter=";")
df_bid_agg = pd.read_csv(f"csv/{timestamp}/bid_agg.csv", delimiter=";")
df_target_price_param = pd.read_csv(f"csv/{timestamp}/target_price_param.csv", delimiter=";")
df_limit_buy = pd.read_csv(f"csv/{timestamp}/limit_buy.csv", delimiter=";")
df_limit_sell = pd.read_csv(f"csv/{timestamp}/limit_sell.csv", delimiter=";")
df_target_asks = pd.read_csv(f"csv/{timestamp}/target_asks.csv", delimiter=";")
df_target_bids = pd.read_csv(f"csv/{timestamp}/target_bids.csv", delimiter=";")

df_market_positions = pd.read_csv(f"csv/{timestamp}/market_positions.csv", delimiter=";")
df_payoffs = pd.read_csv(f"csv/{timestamp}/payoffs.csv", delimiter=";")
df_revenues = pd.read_csv(f"csv/{timestamp}/revenues.csv", delimiter=";")
df_expenses = pd.read_csv(f"csv/{timestamp}/expenses.csv", delimiter=";")
df_prod_costs = pd.read_csv(f"csv/{timestamp}/prod_costs.csv", delimiter=";")
df_penalty_imbalances = pd.read_csv(f"csv/{timestamp}/penalty_imbalances.csv", delimiter=";")
df_imbalances = pd.read_csv(f"csv/{timestamp}/imbalances.csv", delimiter=";")

bidder_colors = ['green', 'purple', 'orange', 'brown', 'pink', 'olive']
ask_color = 'red'
bid_color = 'blue'
match_color = 'slategrey'

In [949]:
print(f'Starting parameters:')
print(f'Aggressiveness ask: {start_aggressiveness_ask}')
print(f'Aggressiveness bid: {start_aggressiveness_bid}')
print(f'Aggressiveness step factor: {aggressiveness_step_factor}')
print(f'Target price param step factor: {target_price_param_step_factor}')
print(f'Bid step factor: {bid_step_factor}')

Starting parameters:
Aggressiveness ask: [-0.6652326074702243, -0.6734011509591631, -0.688625727247617, -0.8606712767190526, -0.6649372291693687, -0.12811034195770454]
Aggressiveness bid: [-0.36420547126573344, -0.8714683847862731, -0.6421796956389263, -0.013205482873518748, -0.8214903392665708, -0.36565437753702146]
Aggressiveness step factor: [0.60312280709188, 0.9701705202485955, 0.6294611081152216, 0.5030144499690888, 0.6493859429095113, 0.95569250750617]
Target price param step factor: [0.8135633858656144, 0.9148928332869344, 0.618589499230966, 0.710167237538968, 0.5413682665228364, 0.611991160226045]
Bid step factor: [1.9672891963578778, 1.8435870074265956, 2.9117649252733626, 2.9930001362086047, 1.7468268117702737, 2.1592314044133687]

In [950]:
df_bidders

,Unnamed: 0,x_demand,x_bought,x_sold,x_da,x_imb,x_re_gen,x_th_gen,x_re_cap,x_th_cap,...,ask_price,bid_price,limit_buy,limit_sell,target_price_param,target_price_param_step_factor,aggressiveness_buy,aggressiveness_sell,aggressiveness_step_factor,bid_step_factor
0,0,-2500.0,0.0,0.0,-2541.354436,41.354436,0.0,0.000000,0.0,0.0,...,11.608184,6.082089,15.0,0.0,-4.0,0.861784,-0.164202,0.010348,0.700243,1.5
1,1,0.0,0.0,0.0,692.148683,7.851317,200.0,500.000000,200.0,500.0,...,11.751201,6.072268,15.0,9.0,-4.0,0.569779,-0.164784,0.024123,0.868446,1.5
2,2,0.0,0.0,0.0,681.730198,7.457721,200.0,489.187920,200.0,500.0,...,11.814947,6.049912,15.0,10.0,-4.0,0.554300,-0.166113,0.023863,0.712762,1.5
3,3,0.0,0.0,0.0,470.000758,-9.184096,200.0,260.816662,200.0,500.0,...,11.938597,6.022847,15.0,12.0,-4.0,0.601502,-0.167732,0.004036,0.552300,1.5
4,4,0.0,0.0,0.0,697.474796,1.963685,200.0,499.438481,200.0,500.0,...,11.805851,6.081738,15.0,11.5,-4.0,0.943790,-0.164223,0.123962,0.962654,1.5
5,5,0.0,0.0,0.0,0.000000,200.000000,200.0,0.000000,200.0,500.0,...,11.633167,6.550269,15.0,0.0,-4.0,0.847692,-0.137932,0.009550,0.680539,1.5

In [951]:
df_game_data

,Unnamed: 0,market,marginal_price,social_welfare,system_imbalance,imbalance_penalty_factor,transaction_price,top_bid,top_ask,equilibrium_price_estimate,volatility,last_event,last_price
0,0,DA,12.0,32325.286963,0.000000,15.0,12.0,NaN,NaN,12.0,0.0,match,12.000000
1,1,ID,NaN,NaN,743.109463,15.0,NaN,0.000000,17.485299,12.0,0.0,ask,17.485299
2,2,ID,NaN,NaN,631.918711,15.0,NaN,0.000000,17.485299,12.0,0.0,ask,17.485299
3,3,ID,NaN,NaN,566.993204,15.0,NaN,0.000000,17.485299,12.0,0.0,ask,17.542078
4,4,ID,NaN,NaN,-280.020029,15.0,NaN,0.909979,17.485299,12.0,0.0,bid,0.909979
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,195,ID,NaN,NaN,226.809178,15.0,NaN,6.017780,11.824644,12.0,0.0,ask,11.824644
196,196,ID,NaN,NaN,236.321169,15.0,NaN,6.017780,11.819904,12.0,0.0,ask,11.819904
197,197,ID,NaN,NaN,252.985024,15.0,NaN,6.017780,11.818324,12.0,0.0,ask,11.818324
198,198,ID,NaN,NaN,249.048527,15.0,NaN,6.017780,11.815792,12.0,0.0,ask,11.815792
199,199,ID,NaN,NaN,249.443063,15.0,NaN,6.017780,11.814947,12.0,0.0,ask,11.814947

In [952]:
df_ask_agg

     Unnamed: 0  bidder_0  bidder_1  bidder_2  bidder_3  bidder_4  bidder_5
0             1 -0.416933 -0.370385 -0.279528 -0.372518 -0.287949 -0.205654
1             2 -0.416933 -0.370385 -0.279528 -0.372518 -0.287949 -0.205654
2             3 -0.317629 -0.287652 -0.279528 -0.318725 -0.275598 -0.205654
3             4 -0.287861 -0.276768 -0.279528 -0.294641 -0.275598 -0.205654
4             5 -0.287861 -0.276768 -0.279528 -0.294641 -0.275598 -0.205654
..          ...       ...       ...       ...       ...       ...       ...
194         195  0.010348  0.015105  0.023863  0.004036  0.110888  0.009550
195         196  0.010348  0.015105  0.023863  0.004036  0.110888  0.009550
196         197  0.010348  0.024123  0.023863  0.004036  0.110888  0.009550
197         198  0.010348  0.024123  0.023863  0.004036  0.110888  0.009550
198         199  0.010348  0.024123  0.023863  0.004036  0.123962  0.009550

[199 rows x 7 columns]

In [953]:
df_bid_agg

     Unnamed: 0  bidder_0  bidder_1  bidder_2  bidder_3  bidder_4  bidder_5
0             1 -0.483646 -0.189675 -0.866684 -0.814972 -0.594439 -0.137932
1             2 -0.483646 -0.189675 -0.866684 -0.814972 -0.594439 -0.137932
2             3 -0.483646 -0.189675 -0.866684 -0.814972 -0.594439 -0.137932
3             4 -0.483646 -0.189675 -0.866684 -0.814972 -0.594439 -0.137932
4             5 -0.483646 -0.189675 -0.673985 -0.694215 -0.594439 -0.137932
..          ...       ...       ...       ...       ...       ...       ...
194         195 -0.164202 -0.164784 -0.166113 -0.167732 -0.164223 -0.137932
195         196 -0.164202 -0.164784 -0.166113 -0.167732 -0.164223 -0.137932
196         197 -0.164202 -0.164784 -0.166113 -0.167732 -0.164223 -0.137932
197         198 -0.164202 -0.164784 -0.166113 -0.167732 -0.164223 -0.137932
198         199 -0.164202 -0.164784 -0.166113 -0.167732 -0.164223 -0.137932

[199 rows x 7 columns]

In [954]:
bidder = 2

bid_price = df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'bid') | (df_bid_logs['match_flag'] == 'match')), 'price']
ask_price = df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'ask') | (df_bid_logs['match_flag'] == 'match')), 'price']

transaction_price = df_bid_logs.loc[df_bid_logs['bidder'] == bidder, 'transaction_price']

In [955]:
df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'match')]

Empty DataFrame
Columns: [Unnamed: 0, bidder, price, volume, transaction_price, match_flag, buyer, seller]
Index: []

In [956]:
df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'ask') | (df_bid_logs['match_flag'] == 'match'))]

,Unnamed: 0,bidder,price,volume,transaction_price,match_flag,buyer,seller
0,1,2.0,17.485299,2000.000000,NaN,ask,NaN,NaN
1,2,2.0,17.485299,2000.000000,NaN,ask,NaN,NaN
20,21,2.0,17.331440,2000.000000,NaN,ask,NaN,NaN
32,33,2.0,17.162015,2000.000000,NaN,ask,NaN,NaN
38,39,2.0,17.008825,2000.000000,NaN,ask,NaN,NaN
43,44,2.0,16.947782,2000.000000,NaN,ask,NaN,NaN
52,53,2.0,16.806601,2000.000000,NaN,ask,NaN,NaN
64,65,2.0,16.507835,2000.000000,NaN,ask,NaN,NaN
65,66,2.0,16.503545,2000.000000,NaN,ask,NaN,NaN
69,70,2.0,16.435859,2000.000000,NaN,ask,NaN,NaN
79,80,2.0,16.191474,2000.000000,NaN,ask,NaN,NaN
80,81,2.0,16.190854,2000.000000,NaN,ask,NaN,NaN
90,91,2.0,15.960464,2000.000000,NaN,ask,NaN,NaN
100,101,2.0,15.678987,2000.000000,NaN,ask,NaN,NaN
110,111,2.0,15.365597,2000.000000,NaN,ask,NaN,NaN
112,113,2.0,15.341842,2000.000000,NaN,ask,NaN,NaN
116,117,2.0,15.200695,2000.000000,NaN,ask,NaN,NaN
131,132,2.0,14.620205,5.856987,NaN,ask,NaN,NaN
132,133,2.0,14.596556,2.083554,NaN,ask,NaN,NaN
153,154,2.0,13.993832,6.043376,NaN,ask,NaN,NaN
154,155,2.0,13.934986,0.827586,NaN,ask,NaN,NaN
155,156,2.0,13.915370,6.593070,NaN,ask,NaN,NaN
162,163,2.0,13.561378,4.333370,NaN,ask,NaN,NaN
163,164,2.0,13.526252,7.016044,NaN,ask,NaN,NaN
166,167,2.0,13.343194,6.349198,NaN,ask,NaN,NaN
169,170,2.0,13.093995,7.256612,NaN,ask,NaN,NaN
172,173,2.0,13.054271,5.731171,NaN,ask,NaN,NaN
174,175,2.0,12.821122,4.147649,NaN,ask,NaN,NaN
176,177,2.0,12.526450,9.735370,NaN,ask,NaN,NaN
190,191,2.0,11.888255,8.540889,NaN,ask,NaN,NaN
193,194,2.0,11.832286,6.251350,NaN,ask,NaN,NaN
197,198,2.0,11.815792,7.464512,NaN,ask,NaN,NaN
198,199,2.0,11.814947,7.457721,NaN,ask,NaN,NaN

In [957]:
### Bids vs Aggressiveness

for bidder in range(n):
    fig = go.Figure()
    

    
    # Add marker for 'bid price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'bid') | (df_bid_logs['match_flag'] == 'match'))].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'bid') | (df_bid_logs['match_flag'] == 'match')), 'price'],
        mode='markers',
        name=f'Bid price',
        line=dict(width=2, color=bid_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'ask price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'ask') | (df_bid_logs['match_flag'] == 'match'))].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & ((df_bid_logs['match_flag'] == 'ask') | (df_bid_logs['match_flag'] == 'match')), 'price'],
        mode='markers',
        name=f'Ask price',
        line=dict(width=2, color=ask_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'transaction price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[df_bid_logs['bidder'] == bidder].index,
        y=df_bid_logs.loc[df_bid_logs['bidder'] == bidder, 'transaction_price'],
        mode='markers',
        name=f'Transaction price',
        line=dict(width=2, color=match_color),
        marker=dict(symbol='x'), 
        yaxis='y'
    ))
    
    # Add bar for 'volume'
    fig.add_trace(go.Bar(
        x=df_bid_logs.loc[df_bid_logs['bidder'] == bidder].index,
        y=df_bid_logs.loc[df_bid_logs['bidder'] == bidder, 'volume'],
        name='Volume',
        width=1.5,
        yaxis='y2',
        marker=dict(color=bidder_colors[bidder]),
    ))
    
    # Add line for 'Ask aggressiveness'
    fig.add_trace(go.Scatter(
        x=df_ask_agg[f'bidder_{bidder}'].index,
        y=-df_ask_agg[f'bidder_{bidder}'],
        mode='lines',
        name='Ask aggressiveness',
        yaxis='y3',
        line=dict(width=2, color=ask_color)  # Adjust line width if necessary
    ))
    
    # Add line for 'Bid aggressiveness'
    fig.add_trace(go.Scatter(
        x=df_bid_agg[f'bidder_{bidder}'].index,
        y=df_bid_agg[f'bidder_{bidder}'],
        mode='lines',
        name='Bid aggressiveness',
        yaxis='y3',
        line=dict(width=2, color=bid_color)  # Adjust line width if necessary
    ))
    
    marginal_price = df_game_data['marginal_price'].iloc[0]
    
    range_y = [0, max_price]
    range_y2 = [0, 500]
    range_y3 = [-1, 1]
    
    # Update layout
    fig.update_layout(
        title=f'Bidder {bidder}',
        xaxis_title='Timestep',
        yaxis=dict(
            title='Price', 
            side='right',
            overlaying='y2',
            position=1,
            range=range_y,
            tickcolor='black',
        ),
        yaxis2=dict(
            title='Volume',
            #side='right',
            position=0,
            range=range_y2,
            ticks='',
            ),
        yaxis3=dict(
            visible=False,
            overlaying='y2',
            range=range_y3,
    ))
    
    # Show the plot
    fig.show()

In [977]:
### Imbalance vs Production

for bidder in range(n):
    fig = go.Figure()

    # Add marker for 'bid price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'bid')].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'bid'), 'price'],
        mode='markers',
        name=f'Bid price',
        line=dict(width=2, color=bid_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'ask price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'ask')].index,
        y=df_bid_logs.loc[(df_bid_logs['bidder'] == bidder) & (df_bid_logs['match_flag'] == 'ask'), 'price'],
        mode='markers',
        name=f'Ask price',
        line=dict(width=2, color=ask_color),  # Adjust line width if necessary
        yaxis='y'
    ))

    # Add marker for 'transaction price'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.loc[df_bid_logs['bidder'] == bidder].index,
        y=df_bid_logs.loc[df_bid_logs['bidder'] == bidder, 'transaction_price'],
        mode='markers',
        name=f'Transaction price',
        line=dict(width=2, color=match_color),
        marker=dict(symbol='x'), 
        yaxis='y'
    ))
    
    # Add line for 'Marginal costs'
    fig.add_trace(go.Scatter(
        x=df_bid_logs.index,
        y=[true_costs[bidder]] * len(df_bid_logs),
        mode='lines',
        name='Marginal costs',
        yaxis='y',
        opacity=0.75,
        line=dict(width=2, color=match_color, dash='dash')  # Adjust line width if necessary
    ))
    
    # Add bar for 'Thermal prod'
    fig.add_trace(go.Bar(
        x=df_x_th_gen[f'bidder_{bidder}'].index,
        y=df_x_th_gen[f'bidder_{bidder}'],
        name='Thermal gen',
        width=1,
        yaxis='y2',
        marker=dict(color='brown'),
    ))
    
    # Add bar for 'RE prod'
    fig.add_trace(go.Bar(
        x=df_x_re_gen[f'bidder_{bidder}'].index,
        y=df_x_re_gen[f'bidder_{bidder}'],
        name='RE gen',
        width=1,
        yaxis='y2',
        marker=dict(color='green'),
    ))
    
    # Add line for 'Imbalance'
    fig.add_trace(go.Scatter(
        x=df_imbalances[f'bidder_{bidder}'].index,
        y=df_imbalances[f'bidder_{bidder}'] + df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name='Imbalance',
        yaxis='y2',
        line=dict(width=2, color=match_color)  # Adjust line width if necessary
    ))
    
    # Add outline for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position outline',
        showlegend=False,
        line=dict(width=4, color='black'),  # Adjust line width if necessary
        yaxis='y2'
    ))

    # Add line for 'market position'
    fig.add_trace(go.Scatter(
        x=df_market_positions[f'bidder_{bidder}'].index,
        y=df_market_positions[f'bidder_{bidder}'],
        mode='lines',
        name=f'Market position',
        line=dict(width=3, color=bidder_colors[bidder]),  # Adjust line width if necessary
        yaxis='y2'
    ))
    
    demand_mean = -2500
    max_imbalance = df_imbalances[f'bidder_{bidder}'].abs().max()
    
    range_y = [0, max_price]
    range_y2 = [0, 1400] if bidder != 0 else [demand_mean - max_imbalance, demand_mean + max_imbalance]
    
    # Update layout
    fig.update_layout(
        title=f'Bidder {bidder}',
        xaxis_title='Timestep',
        barmode='stack',
        #width=800,
        #height=600,
        yaxis=dict(
            title='Price', 
            side='right',
            overlaying='y2',
            position=1,
            range=range_y,
            tickcolor='black',
        ),
        yaxis2=dict(
            title='Volume',
            #side='right',
            position=0,
            range=range_y2,
            ticks='',
            ),
    )
    
    # Show the plot
    fig.show()

In [959]:
### Bid history

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_bid_logs.loc[df_bid_logs['match_flag'] == 'bid', 'price'].index,
    y=df_bid_logs.loc[df_bid_logs['match_flag'] == 'bid', 'price'],
    mode='lines',
    name='Bids',
    line=dict(width=2, color=bid_color)  # Adjust line width if necessary
))

fig.add_trace(go.Scatter(
    x=df_bid_logs.loc[df_bid_logs['match_flag'] == 'ask', 'price'].index,
    y=df_bid_logs.loc[df_bid_logs['match_flag'] == 'ask', 'price'],
    mode='lines',
    name='Asks',
    line=dict(width=2, color=ask_color)  # Adjust line width if necessary
))

# Update layout
fig.update_layout(
    title='Bid history',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [972]:
### Limits

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_limit_sell[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Ask',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_limit_buy[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Bid',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Limits',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [961]:
### Bid-Ask spread

fig = go.Figure()

# Add lines for 'bid'
fig.add_trace(go.Scatter(
    #x=bid_data['index'],
    y=df_game_data['top_bid'],
    mode='lines',
    name='Top bid',
    line=dict(width=2, color=bid_color)  # Adjust line width if necessary
))

# Add lines for 'ask'
fig.add_trace(go.Scatter(
    y=df_game_data['top_ask'],
    mode='lines',
    name='Top Ask',
    marker=dict(size=8, color=ask_color)  # Adjust point size if necessary
))

# Add lines for 'Day-Ahead Preis'
fig.add_trace(go.Scatter(
    #x=bid_data['index'],
    y=[df_game_data.loc[0, 'marginal_price'] for i in range(len(df_game_data))],
    mode='lines',
    name='Day-Ahead price',
    line=dict(width=2)  # Adjust line width if necessary
))

# Add points for 'matches'
fig.add_trace(go.Scatter(
    y=df_game_data['transaction_price'],
    mode='markers',
    name='Matches',
    marker=dict(size=8, color=match_color, symbol='x')  # Adjust point size if necessary
))

# Update layout
fig.update_layout(
    title='Bid-Ask spread',
    xaxis_title='Timesteps',
    yaxis_title='Price',
    legend_title='Type'
)

# Show the plot
fig.show()

In [962]:
### Limits

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_limit_buy[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} limit buy',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_limit_sell[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} limit sell',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))
    
# Update layout
fig.update_layout(
    title='Limits',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [963]:
### Target prices

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_target_asks[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} target ask',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_target_bids[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} target bid',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))
    
# Update layout
fig.update_layout(
    title='Target prices',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [964]:
### Aggressiveness

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_ask_agg[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Ask',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))
    
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_bid_agg[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Bid',
        line=dict(width=2, color=bidder_colors[bidder], dash='dash')  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Aggressiveness',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [965]:
### Target price param

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_target_price_param[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder} Target price param',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Target price param',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [966]:
### Imbalance price

fig_volatility = go.Figure()

fig_volatility.add_trace(go.Scatter
(
    x=df_game_data.index,
    y=df_game_data['imbalance_penalty_factor'],
    mode='lines',
    name='Volatility',
    line=dict(width=2)
))

fig_volatility.update_layout(title='Imbalance penalty price')
fig_volatility.show()

In [967]:
### Payoffs

fig = go.Figure()

for bidder in range(n):
    fig.add_trace(go.Scatter(
        #x=bid_data['index'],
        y=df_payoffs[f'bidder_{bidder}'],
        mode='lines',
        name=f'Bidder {bidder}',
        line=dict(width=2, color=bidder_colors[bidder])  # Adjust line width if necessary
    ))

# Update layout
fig.update_layout(
    title='Payoffs',
    xaxis_title='Index',
    yaxis_title='Value',
    legend_title='Type'
)

# Show the plot
fig.show()

In [968]:
### Volatility

fig_volatility = go.Figure()

fig_volatility.add_trace(go.Scatter
(
    x=df_game_data.index,
    y=df_game_data['volatility'],
    mode='lines',
    name='Volatility',
    line=dict(width=2)
))

fig_volatility.update_layout(title='Volatility')
fig_volatility.show()